name = "AllocArrays"
uuid = "5c00bae2-1499-4716-9206-27f63fd08a44"
authors = ["Eric P. Hanson"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
